//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadABook.VocalRecallService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/VocalRecallService.DataContract")]
    [System.SerializableAttribute()]
    public partial class Word : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AlternativePictureUrlsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ReadABook.VocalRecallService.AsyncWordResult AsyncWordResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CultureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> FrequencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FrequencyLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PictureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PronunciationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SelectedPictureUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WordIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AlternativePictureUrls {
            get {
                return this.AlternativePictureUrlsField;
            }
            set {
                if ((object.ReferenceEquals(this.AlternativePictureUrlsField, value) != true)) {
                    this.AlternativePictureUrlsField = value;
                    this.RaisePropertyChanged("AlternativePictureUrls");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ReadABook.VocalRecallService.AsyncWordResult AsyncWordResult {
            get {
                return this.AsyncWordResultField;
            }
            set {
                if ((this.AsyncWordResultField.Equals(value) != true)) {
                    this.AsyncWordResultField = value;
                    this.RaisePropertyChanged("AsyncWordResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FrequencyLastUpdated {
            get {
                return this.FrequencyLastUpdatedField;
            }
            set {
                if ((this.FrequencyLastUpdatedField.Equals(value) != true)) {
                    this.FrequencyLastUpdatedField = value;
                    this.RaisePropertyChanged("FrequencyLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Index {
            get {
                return this.IndexField;
            }
            set {
                if ((this.IndexField.Equals(value) != true)) {
                    this.IndexField = value;
                    this.RaisePropertyChanged("Index");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Pronunciation {
            get {
                return this.PronunciationField;
            }
            set {
                if ((object.ReferenceEquals(this.PronunciationField, value) != true)) {
                    this.PronunciationField = value;
                    this.RaisePropertyChanged("Pronunciation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelectedPictureUrl {
            get {
                return this.SelectedPictureUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.SelectedPictureUrlField, value) != true)) {
                    this.SelectedPictureUrlField = value;
                    this.RaisePropertyChanged("SelectedPictureUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordId {
            get {
                return this.WordIdField;
            }
            set {
                if ((this.WordIdField.Equals(value) != true)) {
                    this.WordIdField = value;
                    this.RaisePropertyChanged("WordId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }

		public override string ToString()
		{
			return this.Text;
		}
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsyncWordResult", Namespace="http://schemas.datacontract.org/2004/07/VocalRecallService.DataContract")]
    public enum AsyncWordResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllOk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadingPronunciation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadingPicture = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadingTranslation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingEntry = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Culture", Namespace="http://schemas.datacontract.org/2004/07/VocalRecallService.DataContract")]
    [System.SerializableAttribute()]
    public partial class Culture : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CultureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureIsoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureIso {
            get {
                return this.CultureIsoField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureIsoField, value) != true)) {
                    this.CultureIsoField = value;
                    this.RaisePropertyChanged("CultureIso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/VocalRecallService.DataContract")]
    [System.SerializableAttribute()]
    public partial class UserInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CultureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SessionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentLevel {
            get {
                return this.CurrentLevelField;
            }
            set {
                if ((this.CurrentLevelField.Equals(value) != true)) {
                    this.CurrentLevelField = value;
                    this.RaisePropertyChanged("CurrentLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Translation", Namespace="http://schemas.datacontract.org/2004/07/VocalRecallService.DataContract")]
    [System.SerializableAttribute()]
    public partial class Translation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CultureIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OriginalWordIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartOfSpeechField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RareField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RootWordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TranslationIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UncommonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Common {
            get {
                return this.CommonField;
            }
            set {
                if ((object.ReferenceEquals(this.CommonField, value) != true)) {
                    this.CommonField = value;
                    this.RaisePropertyChanged("Common");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastUpdated {
            get {
                return this.LastUpdatedField;
            }
            set {
                if ((this.LastUpdatedField.Equals(value) != true)) {
                    this.LastUpdatedField = value;
                    this.RaisePropertyChanged("LastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginalWordId {
            get {
                return this.OriginalWordIdField;
            }
            set {
                if ((this.OriginalWordIdField.Equals(value) != true)) {
                    this.OriginalWordIdField = value;
                    this.RaisePropertyChanged("OriginalWordId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartOfSpeech {
            get {
                return this.PartOfSpeechField;
            }
            set {
                if ((object.ReferenceEquals(this.PartOfSpeechField, value) != true)) {
                    this.PartOfSpeechField = value;
                    this.RaisePropertyChanged("PartOfSpeech");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rare {
            get {
                return this.RareField;
            }
            set {
                if ((object.ReferenceEquals(this.RareField, value) != true)) {
                    this.RareField = value;
                    this.RaisePropertyChanged("Rare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RootWord {
            get {
                return this.RootWordField;
            }
            set {
                if ((object.ReferenceEquals(this.RootWordField, value) != true)) {
                    this.RootWordField = value;
                    this.RaisePropertyChanged("RootWord");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TranslationId {
            get {
                return this.TranslationIdField;
            }
            set {
                if ((this.TranslationIdField.Equals(value) != true)) {
                    this.TranslationIdField = value;
                    this.RaisePropertyChanged("TranslationId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Uncommon {
            get {
                return this.UncommonField;
            }
            set {
                if ((object.ReferenceEquals(this.UncommonField, value) != true)) {
                    this.UncommonField = value;
                    this.RaisePropertyChanged("Uncommon");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VocalRecallService.IVocalRecallService")]
    public interface IVocalRecallService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/DeleteWords", ReplyAction="http://tempuri.org/IVocalRecallService/DeleteWordsResponse")]
        void DeleteWords(int cultureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/UploadWords", ReplyAction="http://tempuri.org/IVocalRecallService/UploadWordsResponse")]
        int UploadWords(int cultureId, ReadABook.VocalRecallService.Word[] words);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/ListCultures", ReplyAction="http://tempuri.org/IVocalRecallService/ListCulturesResponse")]
        ReadABook.VocalRecallService.Culture[] ListCultures();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/AuthenticateUser", ReplyAction="http://tempuri.org/IVocalRecallService/AuthenticateUserResponse")]
        int AuthenticateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/GetUserInfo", ReplyAction="http://tempuri.org/IVocalRecallService/GetUserInfoResponse")]
        ReadABook.VocalRecallService.UserInfo GetUserInfo(string username, int sessionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/GetWord", ReplyAction="http://tempuri.org/IVocalRecallService/GetWordResponse")]
        ReadABook.VocalRecallService.Word GetWord(int wordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/GetTranslations", ReplyAction="http://tempuri.org/IVocalRecallService/GetTranslationsResponse")]
        ReadABook.VocalRecallService.Translation[] GetTranslations(int wordId, int cultureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/GetWords", ReplyAction="http://tempuri.org/IVocalRecallService/GetWordsResponse")]
        ReadABook.VocalRecallService.Word[] GetWords(int cultureId, int frequencyMinimum, int frequencyMaximum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/Get10Words", ReplyAction="http://tempuri.org/IVocalRecallService/Get10WordsResponse")]
        ReadABook.VocalRecallService.Word[] Get10Words(int cultureId, int top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/DeletePicture", ReplyAction="http://tempuri.org/IVocalRecallService/DeletePictureResponse")]
        void DeletePicture(int wordId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/ResetWordFrequencies", ReplyAction="http://tempuri.org/IVocalRecallService/ResetWordFrequenciesResponse")]
        void ResetWordFrequencies(int cultureId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/UpdateCultureStatistics", ReplyAction="http://tempuri.org/IVocalRecallService/UpdateCultureStatisticsResponse")]
        void UpdateCultureStatistics(int cultureId, long totalBooksRead, long totalWordsProcessed, long totalWordCount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/UploadOrUpdateFrequencyForWords", ReplyAction="http://tempuri.org/IVocalRecallService/UploadOrUpdateFrequencyForWordsResponse")]
        void UploadOrUpdateFrequencyForWords(int cultureId, ReadABook.VocalRecallService.Word[] wordList);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVocalRecallService/GetTopWords", ReplyAction="http://tempuri.org/IVocalRecallService/GetTopWordsResponse")]
        ReadABook.VocalRecallService.Word[] GetTopWords(int cultureId, int topCount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVocalRecallServiceChannel : ReadABook.VocalRecallService.IVocalRecallService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VocalRecallServiceClient : System.ServiceModel.ClientBase<ReadABook.VocalRecallService.IVocalRecallService>, ReadABook.VocalRecallService.IVocalRecallService {
        
        public VocalRecallServiceClient() {
        }
        
        public VocalRecallServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VocalRecallServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocalRecallServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VocalRecallServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DeleteWords(int cultureId) {
            base.Channel.DeleteWords(cultureId);
        }
        
        public int UploadWords(int cultureId, ReadABook.VocalRecallService.Word[] words) {
            return base.Channel.UploadWords(cultureId, words);
        }
        
        public ReadABook.VocalRecallService.Culture[] ListCultures() {
            return base.Channel.ListCultures();
        }
        
        public int AuthenticateUser(string username, string password) {
            return base.Channel.AuthenticateUser(username, password);
        }
        
        public ReadABook.VocalRecallService.UserInfo GetUserInfo(string username, int sessionId) {
            return base.Channel.GetUserInfo(username, sessionId);
        }
        
        public ReadABook.VocalRecallService.Word GetWord(int wordId) {
            return base.Channel.GetWord(wordId);
        }
        
        public ReadABook.VocalRecallService.Translation[] GetTranslations(int wordId, int cultureId) {
            return base.Channel.GetTranslations(wordId, cultureId);
        }
        
        public ReadABook.VocalRecallService.Word[] GetWords(int cultureId, int frequencyMinimum, int frequencyMaximum) {
            return base.Channel.GetWords(cultureId, frequencyMinimum, frequencyMaximum);
        }
        
        public ReadABook.VocalRecallService.Word[] Get10Words(int cultureId, int top) {
            return base.Channel.Get10Words(cultureId, top);
        }
        
        public void DeletePicture(int wordId) {
            base.Channel.DeletePicture(wordId);
        }
        
        public void ResetWordFrequencies(int cultureId) {
            base.Channel.ResetWordFrequencies(cultureId);
        }
        
        public void UpdateCultureStatistics(int cultureId, long totalBooksRead, long totalWordsProcessed, long totalWordCount) {
            base.Channel.UpdateCultureStatistics(cultureId, totalBooksRead, totalWordsProcessed, totalWordCount);
        }
        
        public void UploadOrUpdateFrequencyForWords(int cultureId, ReadABook.VocalRecallService.Word[] wordList) {
            base.Channel.UploadOrUpdateFrequencyForWords(cultureId, wordList);
        }
        
        public ReadABook.VocalRecallService.Word[] GetTopWords(int cultureId, int topCount) {
            return base.Channel.GetTopWords(cultureId, topCount);
        }
    }
}
