//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.50826.0
// 
namespace VocalRecall.SuggestopediaService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Word", Namespace="http://schemas.datacontract.org/2004/07/SuggestopediaService.DataContract")]
    public partial class Word : object, System.ComponentModel.INotifyPropertyChanged {
        
        private VocalRecall.SuggestopediaService.AsyncWordResult AsyncWordResultField;
        
        private int CultureIdField;
        
        private System.Nullable<int> FrequencyField;
        
        private byte[] PictureField;
        
        private byte[] PronunciationField;
        
        private string TextField;
        
        private int WordIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VocalRecall.SuggestopediaService.AsyncWordResult AsyncWordResult {
            get {
                return this.AsyncWordResultField;
            }
            set {
                if ((this.AsyncWordResultField.Equals(value) != true)) {
                    this.AsyncWordResultField = value;
                    this.RaisePropertyChanged("AsyncWordResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Frequency {
            get {
                return this.FrequencyField;
            }
            set {
                if ((this.FrequencyField.Equals(value) != true)) {
                    this.FrequencyField = value;
                    this.RaisePropertyChanged("Frequency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Picture {
            get {
                return this.PictureField;
            }
            set {
                if ((object.ReferenceEquals(this.PictureField, value) != true)) {
                    this.PictureField = value;
                    this.RaisePropertyChanged("Picture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Pronunciation {
            get {
                return this.PronunciationField;
            }
            set {
                if ((object.ReferenceEquals(this.PronunciationField, value) != true)) {
                    this.PronunciationField = value;
                    this.RaisePropertyChanged("Pronunciation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WordId {
            get {
                return this.WordIdField;
            }
            set {
                if ((this.WordIdField.Equals(value) != true)) {
                    this.WordIdField = value;
                    this.RaisePropertyChanged("WordId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AsyncWordResult", Namespace="http://schemas.datacontract.org/2004/07/SuggestopediaService.DataContract")]
    public enum AsyncWordResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AllOk = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadingPronunciation = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadingPicture = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DownloadingTranslation = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MissingEntry = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Culture", Namespace="http://schemas.datacontract.org/2004/07/SuggestopediaService.DataContract")]
    public partial class Culture : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CultureIdField;
        
        private string CultureIsoField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureIso {
            get {
                return this.CultureIsoField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureIsoField, value) != true)) {
                    this.CultureIsoField = value;
                    this.RaisePropertyChanged("CultureIso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://schemas.datacontract.org/2004/07/SuggestopediaService.DataContract")]
    public partial class UserInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int CultureIdField;
        
        private int CurrentLevelField;
        
        private int SessionIdField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CultureId {
            get {
                return this.CultureIdField;
            }
            set {
                if ((this.CultureIdField.Equals(value) != true)) {
                    this.CultureIdField = value;
                    this.RaisePropertyChanged("CultureId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentLevel {
            get {
                return this.CurrentLevelField;
            }
            set {
                if ((this.CurrentLevelField.Equals(value) != true)) {
                    this.CurrentLevelField = value;
                    this.RaisePropertyChanged("CurrentLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SessionId {
            get {
                return this.SessionIdField;
            }
            set {
                if ((this.SessionIdField.Equals(value) != true)) {
                    this.SessionIdField = value;
                    this.RaisePropertyChanged("SessionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SuggestopediaService.ISuggestopediaService")]
    public interface ISuggestopediaService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/DeleteWords", ReplyAction="http://tempuri.org/ISuggestopediaService/DeleteWordsResponse")]
        System.IAsyncResult BeginDeleteWords(int cultureId, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteWords(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/UploadWords", ReplyAction="http://tempuri.org/ISuggestopediaService/UploadWordsResponse")]
        System.IAsyncResult BeginUploadWords(int cultureId, System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> words, System.AsyncCallback callback, object asyncState);
        
        int EndUploadWords(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/ListCultures", ReplyAction="http://tempuri.org/ISuggestopediaService/ListCulturesResponse")]
        System.IAsyncResult BeginListCultures(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture> EndListCultures(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/AuthenticateUser", ReplyAction="http://tempuri.org/ISuggestopediaService/AuthenticateUserResponse")]
        System.IAsyncResult BeginAuthenticateUser(string username, string password, System.AsyncCallback callback, object asyncState);
        
        int EndAuthenticateUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/GetUserInfo", ReplyAction="http://tempuri.org/ISuggestopediaService/GetUserInfoResponse")]
        System.IAsyncResult BeginGetUserInfo(string username, int sessionId, System.AsyncCallback callback, object asyncState);
        
        VocalRecall.SuggestopediaService.UserInfo EndGetUserInfo(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/GetWord", ReplyAction="http://tempuri.org/ISuggestopediaService/GetWordResponse")]
        System.IAsyncResult BeginGetWord(int wordId, System.AsyncCallback callback, object asyncState);
        
        VocalRecall.SuggestopediaService.Word EndGetWord(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/GetTranslation", ReplyAction="http://tempuri.org/ISuggestopediaService/GetTranslationResponse")]
        System.IAsyncResult BeginGetTranslation(int wordId, int cultureId, System.AsyncCallback callback, object asyncState);
        
        VocalRecall.SuggestopediaService.Word EndGetTranslation(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/GetWords", ReplyAction="http://tempuri.org/ISuggestopediaService/GetWordsResponse")]
        System.IAsyncResult BeginGetWords(int cultureId, int frequencyMinimum, int frequencyMaximum, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> EndGetWords(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/Get10Words", ReplyAction="http://tempuri.org/ISuggestopediaService/Get10WordsResponse")]
        System.IAsyncResult BeginGet10Words(int cultureId, int top, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> EndGet10Words(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISuggestopediaService/DeletePicture", ReplyAction="http://tempuri.org/ISuggestopediaService/DeletePictureResponse")]
        System.IAsyncResult BeginDeletePicture(int wordId, System.AsyncCallback callback, object asyncState);
        
        void EndDeletePicture(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISuggestopediaServiceChannel : VocalRecall.SuggestopediaService.ISuggestopediaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UploadWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListCulturesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListCulturesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public AuthenticateUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetUserInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetUserInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VocalRecall.SuggestopediaService.UserInfo Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VocalRecall.SuggestopediaService.UserInfo)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VocalRecall.SuggestopediaService.Word Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VocalRecall.SuggestopediaService.Word)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetTranslationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetTranslationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VocalRecall.SuggestopediaService.Word Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VocalRecall.SuggestopediaService.Word)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetWordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Get10WordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public Get10WordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SuggestopediaServiceClient : System.ServiceModel.ClientBase<VocalRecall.SuggestopediaService.ISuggestopediaService>, VocalRecall.SuggestopediaService.ISuggestopediaService {
        
        private BeginOperationDelegate onBeginDeleteWordsDelegate;
        
        private EndOperationDelegate onEndDeleteWordsDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteWordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginUploadWordsDelegate;
        
        private EndOperationDelegate onEndUploadWordsDelegate;
        
        private System.Threading.SendOrPostCallback onUploadWordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginListCulturesDelegate;
        
        private EndOperationDelegate onEndListCulturesDelegate;
        
        private System.Threading.SendOrPostCallback onListCulturesCompletedDelegate;
        
        private BeginOperationDelegate onBeginAuthenticateUserDelegate;
        
        private EndOperationDelegate onEndAuthenticateUserDelegate;
        
        private System.Threading.SendOrPostCallback onAuthenticateUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetUserInfoDelegate;
        
        private EndOperationDelegate onEndGetUserInfoDelegate;
        
        private System.Threading.SendOrPostCallback onGetUserInfoCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWordDelegate;
        
        private EndOperationDelegate onEndGetWordDelegate;
        
        private System.Threading.SendOrPostCallback onGetWordCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetTranslationDelegate;
        
        private EndOperationDelegate onEndGetTranslationDelegate;
        
        private System.Threading.SendOrPostCallback onGetTranslationCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWordsDelegate;
        
        private EndOperationDelegate onEndGetWordsDelegate;
        
        private System.Threading.SendOrPostCallback onGetWordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGet10WordsDelegate;
        
        private EndOperationDelegate onEndGet10WordsDelegate;
        
        private System.Threading.SendOrPostCallback onGet10WordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeletePictureDelegate;
        
        private EndOperationDelegate onEndDeletePictureDelegate;
        
        private System.Threading.SendOrPostCallback onDeletePictureCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SuggestopediaServiceClient() {
        }
        
        public SuggestopediaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SuggestopediaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuggestopediaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SuggestopediaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteWordsCompleted;
        
        public event System.EventHandler<UploadWordsCompletedEventArgs> UploadWordsCompleted;
        
        public event System.EventHandler<ListCulturesCompletedEventArgs> ListCulturesCompleted;
        
        public event System.EventHandler<AuthenticateUserCompletedEventArgs> AuthenticateUserCompleted;
        
        public event System.EventHandler<GetUserInfoCompletedEventArgs> GetUserInfoCompleted;
        
        public event System.EventHandler<GetWordCompletedEventArgs> GetWordCompleted;
        
        public event System.EventHandler<GetTranslationCompletedEventArgs> GetTranslationCompleted;
        
        public event System.EventHandler<GetWordsCompletedEventArgs> GetWordsCompleted;
        
        public event System.EventHandler<Get10WordsCompletedEventArgs> Get10WordsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeletePictureCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginDeleteWords(int cultureId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteWords(cultureId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void VocalRecall.SuggestopediaService.ISuggestopediaService.EndDeleteWords(System.IAsyncResult result) {
            base.Channel.EndDeleteWords(result);
        }
        
        private System.IAsyncResult OnBeginDeleteWords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cultureId = ((int)(inValues[0]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginDeleteWords(cultureId, callback, asyncState);
        }
        
        private object[] OnEndDeleteWords(System.IAsyncResult result) {
            ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndDeleteWords(result);
            return null;
        }
        
        private void OnDeleteWordsCompleted(object state) {
            if ((this.DeleteWordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteWordsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteWordsAsync(int cultureId) {
            this.DeleteWordsAsync(cultureId, null);
        }
        
        public void DeleteWordsAsync(int cultureId, object userState) {
            if ((this.onBeginDeleteWordsDelegate == null)) {
                this.onBeginDeleteWordsDelegate = new BeginOperationDelegate(this.OnBeginDeleteWords);
            }
            if ((this.onEndDeleteWordsDelegate == null)) {
                this.onEndDeleteWordsDelegate = new EndOperationDelegate(this.OnEndDeleteWords);
            }
            if ((this.onDeleteWordsCompletedDelegate == null)) {
                this.onDeleteWordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteWordsCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteWordsDelegate, new object[] {
                        cultureId}, this.onEndDeleteWordsDelegate, this.onDeleteWordsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginUploadWords(int cultureId, System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> words, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUploadWords(cultureId, words, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int VocalRecall.SuggestopediaService.ISuggestopediaService.EndUploadWords(System.IAsyncResult result) {
            return base.Channel.EndUploadWords(result);
        }
        
        private System.IAsyncResult OnBeginUploadWords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cultureId = ((int)(inValues[0]));
            System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> words = ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word>)(inValues[1]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginUploadWords(cultureId, words, callback, asyncState);
        }
        
        private object[] OnEndUploadWords(System.IAsyncResult result) {
            int retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndUploadWords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUploadWordsCompleted(object state) {
            if ((this.UploadWordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UploadWordsCompleted(this, new UploadWordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UploadWordsAsync(int cultureId, System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> words) {
            this.UploadWordsAsync(cultureId, words, null);
        }
        
        public void UploadWordsAsync(int cultureId, System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> words, object userState) {
            if ((this.onBeginUploadWordsDelegate == null)) {
                this.onBeginUploadWordsDelegate = new BeginOperationDelegate(this.OnBeginUploadWords);
            }
            if ((this.onEndUploadWordsDelegate == null)) {
                this.onEndUploadWordsDelegate = new EndOperationDelegate(this.OnEndUploadWords);
            }
            if ((this.onUploadWordsCompletedDelegate == null)) {
                this.onUploadWordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUploadWordsCompleted);
            }
            base.InvokeAsync(this.onBeginUploadWordsDelegate, new object[] {
                        cultureId,
                        words}, this.onEndUploadWordsDelegate, this.onUploadWordsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginListCultures(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListCultures(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture> VocalRecall.SuggestopediaService.ISuggestopediaService.EndListCultures(System.IAsyncResult result) {
            return base.Channel.EndListCultures(result);
        }
        
        private System.IAsyncResult OnBeginListCultures(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginListCultures(callback, asyncState);
        }
        
        private object[] OnEndListCultures(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture> retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndListCultures(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListCulturesCompleted(object state) {
            if ((this.ListCulturesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListCulturesCompleted(this, new ListCulturesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListCulturesAsync() {
            this.ListCulturesAsync(null);
        }
        
        public void ListCulturesAsync(object userState) {
            if ((this.onBeginListCulturesDelegate == null)) {
                this.onBeginListCulturesDelegate = new BeginOperationDelegate(this.OnBeginListCultures);
            }
            if ((this.onEndListCulturesDelegate == null)) {
                this.onEndListCulturesDelegate = new EndOperationDelegate(this.OnEndListCultures);
            }
            if ((this.onListCulturesCompletedDelegate == null)) {
                this.onListCulturesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListCulturesCompleted);
            }
            base.InvokeAsync(this.onBeginListCulturesDelegate, null, this.onEndListCulturesDelegate, this.onListCulturesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginAuthenticateUser(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAuthenticateUser(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int VocalRecall.SuggestopediaService.ISuggestopediaService.EndAuthenticateUser(System.IAsyncResult result) {
            return base.Channel.EndAuthenticateUser(result);
        }
        
        private System.IAsyncResult OnBeginAuthenticateUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginAuthenticateUser(username, password, callback, asyncState);
        }
        
        private object[] OnEndAuthenticateUser(System.IAsyncResult result) {
            int retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndAuthenticateUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnAuthenticateUserCompleted(object state) {
            if ((this.AuthenticateUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateUserCompleted(this, new AuthenticateUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AuthenticateUserAsync(string username, string password) {
            this.AuthenticateUserAsync(username, password, null);
        }
        
        public void AuthenticateUserAsync(string username, string password, object userState) {
            if ((this.onBeginAuthenticateUserDelegate == null)) {
                this.onBeginAuthenticateUserDelegate = new BeginOperationDelegate(this.OnBeginAuthenticateUser);
            }
            if ((this.onEndAuthenticateUserDelegate == null)) {
                this.onEndAuthenticateUserDelegate = new EndOperationDelegate(this.OnEndAuthenticateUser);
            }
            if ((this.onAuthenticateUserCompletedDelegate == null)) {
                this.onAuthenticateUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateUserCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateUserDelegate, new object[] {
                        username,
                        password}, this.onEndAuthenticateUserDelegate, this.onAuthenticateUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginGetUserInfo(string username, int sessionId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetUserInfo(username, sessionId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VocalRecall.SuggestopediaService.UserInfo VocalRecall.SuggestopediaService.ISuggestopediaService.EndGetUserInfo(System.IAsyncResult result) {
            return base.Channel.EndGetUserInfo(result);
        }
        
        private System.IAsyncResult OnBeginGetUserInfo(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            int sessionId = ((int)(inValues[1]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginGetUserInfo(username, sessionId, callback, asyncState);
        }
        
        private object[] OnEndGetUserInfo(System.IAsyncResult result) {
            VocalRecall.SuggestopediaService.UserInfo retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndGetUserInfo(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetUserInfoCompleted(object state) {
            if ((this.GetUserInfoCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetUserInfoCompleted(this, new GetUserInfoCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetUserInfoAsync(string username, int sessionId) {
            this.GetUserInfoAsync(username, sessionId, null);
        }
        
        public void GetUserInfoAsync(string username, int sessionId, object userState) {
            if ((this.onBeginGetUserInfoDelegate == null)) {
                this.onBeginGetUserInfoDelegate = new BeginOperationDelegate(this.OnBeginGetUserInfo);
            }
            if ((this.onEndGetUserInfoDelegate == null)) {
                this.onEndGetUserInfoDelegate = new EndOperationDelegate(this.OnEndGetUserInfo);
            }
            if ((this.onGetUserInfoCompletedDelegate == null)) {
                this.onGetUserInfoCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetUserInfoCompleted);
            }
            base.InvokeAsync(this.onBeginGetUserInfoDelegate, new object[] {
                        username,
                        sessionId}, this.onEndGetUserInfoDelegate, this.onGetUserInfoCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginGetWord(int wordId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWord(wordId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VocalRecall.SuggestopediaService.Word VocalRecall.SuggestopediaService.ISuggestopediaService.EndGetWord(System.IAsyncResult result) {
            return base.Channel.EndGetWord(result);
        }
        
        private System.IAsyncResult OnBeginGetWord(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int wordId = ((int)(inValues[0]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginGetWord(wordId, callback, asyncState);
        }
        
        private object[] OnEndGetWord(System.IAsyncResult result) {
            VocalRecall.SuggestopediaService.Word retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndGetWord(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWordCompleted(object state) {
            if ((this.GetWordCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWordCompleted(this, new GetWordCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWordAsync(int wordId) {
            this.GetWordAsync(wordId, null);
        }
        
        public void GetWordAsync(int wordId, object userState) {
            if ((this.onBeginGetWordDelegate == null)) {
                this.onBeginGetWordDelegate = new BeginOperationDelegate(this.OnBeginGetWord);
            }
            if ((this.onEndGetWordDelegate == null)) {
                this.onEndGetWordDelegate = new EndOperationDelegate(this.OnEndGetWord);
            }
            if ((this.onGetWordCompletedDelegate == null)) {
                this.onGetWordCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWordCompleted);
            }
            base.InvokeAsync(this.onBeginGetWordDelegate, new object[] {
                        wordId}, this.onEndGetWordDelegate, this.onGetWordCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginGetTranslation(int wordId, int cultureId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetTranslation(wordId, cultureId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VocalRecall.SuggestopediaService.Word VocalRecall.SuggestopediaService.ISuggestopediaService.EndGetTranslation(System.IAsyncResult result) {
            return base.Channel.EndGetTranslation(result);
        }
        
        private System.IAsyncResult OnBeginGetTranslation(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int wordId = ((int)(inValues[0]));
            int cultureId = ((int)(inValues[1]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginGetTranslation(wordId, cultureId, callback, asyncState);
        }
        
        private object[] OnEndGetTranslation(System.IAsyncResult result) {
            VocalRecall.SuggestopediaService.Word retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndGetTranslation(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetTranslationCompleted(object state) {
            if ((this.GetTranslationCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetTranslationCompleted(this, new GetTranslationCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetTranslationAsync(int wordId, int cultureId) {
            this.GetTranslationAsync(wordId, cultureId, null);
        }
        
        public void GetTranslationAsync(int wordId, int cultureId, object userState) {
            if ((this.onBeginGetTranslationDelegate == null)) {
                this.onBeginGetTranslationDelegate = new BeginOperationDelegate(this.OnBeginGetTranslation);
            }
            if ((this.onEndGetTranslationDelegate == null)) {
                this.onEndGetTranslationDelegate = new EndOperationDelegate(this.OnEndGetTranslation);
            }
            if ((this.onGetTranslationCompletedDelegate == null)) {
                this.onGetTranslationCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetTranslationCompleted);
            }
            base.InvokeAsync(this.onBeginGetTranslationDelegate, new object[] {
                        wordId,
                        cultureId}, this.onEndGetTranslationDelegate, this.onGetTranslationCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginGetWords(int cultureId, int frequencyMinimum, int frequencyMaximum, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWords(cultureId, frequencyMinimum, frequencyMaximum, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> VocalRecall.SuggestopediaService.ISuggestopediaService.EndGetWords(System.IAsyncResult result) {
            return base.Channel.EndGetWords(result);
        }
        
        private System.IAsyncResult OnBeginGetWords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cultureId = ((int)(inValues[0]));
            int frequencyMinimum = ((int)(inValues[1]));
            int frequencyMaximum = ((int)(inValues[2]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginGetWords(cultureId, frequencyMinimum, frequencyMaximum, callback, asyncState);
        }
        
        private object[] OnEndGetWords(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndGetWords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWordsCompleted(object state) {
            if ((this.GetWordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWordsCompleted(this, new GetWordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWordsAsync(int cultureId, int frequencyMinimum, int frequencyMaximum) {
            this.GetWordsAsync(cultureId, frequencyMinimum, frequencyMaximum, null);
        }
        
        public void GetWordsAsync(int cultureId, int frequencyMinimum, int frequencyMaximum, object userState) {
            if ((this.onBeginGetWordsDelegate == null)) {
                this.onBeginGetWordsDelegate = new BeginOperationDelegate(this.OnBeginGetWords);
            }
            if ((this.onEndGetWordsDelegate == null)) {
                this.onEndGetWordsDelegate = new EndOperationDelegate(this.OnEndGetWords);
            }
            if ((this.onGetWordsCompletedDelegate == null)) {
                this.onGetWordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWordsCompleted);
            }
            base.InvokeAsync(this.onBeginGetWordsDelegate, new object[] {
                        cultureId,
                        frequencyMinimum,
                        frequencyMaximum}, this.onEndGetWordsDelegate, this.onGetWordsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginGet10Words(int cultureId, int top, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGet10Words(cultureId, top, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> VocalRecall.SuggestopediaService.ISuggestopediaService.EndGet10Words(System.IAsyncResult result) {
            return base.Channel.EndGet10Words(result);
        }
        
        private System.IAsyncResult OnBeginGet10Words(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int cultureId = ((int)(inValues[0]));
            int top = ((int)(inValues[1]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginGet10Words(cultureId, top, callback, asyncState);
        }
        
        private object[] OnEndGet10Words(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> retVal = ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndGet10Words(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGet10WordsCompleted(object state) {
            if ((this.Get10WordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.Get10WordsCompleted(this, new Get10WordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void Get10WordsAsync(int cultureId, int top) {
            this.Get10WordsAsync(cultureId, top, null);
        }
        
        public void Get10WordsAsync(int cultureId, int top, object userState) {
            if ((this.onBeginGet10WordsDelegate == null)) {
                this.onBeginGet10WordsDelegate = new BeginOperationDelegate(this.OnBeginGet10Words);
            }
            if ((this.onEndGet10WordsDelegate == null)) {
                this.onEndGet10WordsDelegate = new EndOperationDelegate(this.OnEndGet10Words);
            }
            if ((this.onGet10WordsCompletedDelegate == null)) {
                this.onGet10WordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGet10WordsCompleted);
            }
            base.InvokeAsync(this.onBeginGet10WordsDelegate, new object[] {
                        cultureId,
                        top}, this.onEndGet10WordsDelegate, this.onGet10WordsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VocalRecall.SuggestopediaService.ISuggestopediaService.BeginDeletePicture(int wordId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeletePicture(wordId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void VocalRecall.SuggestopediaService.ISuggestopediaService.EndDeletePicture(System.IAsyncResult result) {
            base.Channel.EndDeletePicture(result);
        }
        
        private System.IAsyncResult OnBeginDeletePicture(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int wordId = ((int)(inValues[0]));
            return ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).BeginDeletePicture(wordId, callback, asyncState);
        }
        
        private object[] OnEndDeletePicture(System.IAsyncResult result) {
            ((VocalRecall.SuggestopediaService.ISuggestopediaService)(this)).EndDeletePicture(result);
            return null;
        }
        
        private void OnDeletePictureCompleted(object state) {
            if ((this.DeletePictureCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeletePictureCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeletePictureAsync(int wordId) {
            this.DeletePictureAsync(wordId, null);
        }
        
        public void DeletePictureAsync(int wordId, object userState) {
            if ((this.onBeginDeletePictureDelegate == null)) {
                this.onBeginDeletePictureDelegate = new BeginOperationDelegate(this.OnBeginDeletePicture);
            }
            if ((this.onEndDeletePictureDelegate == null)) {
                this.onEndDeletePictureDelegate = new EndOperationDelegate(this.OnEndDeletePicture);
            }
            if ((this.onDeletePictureCompletedDelegate == null)) {
                this.onDeletePictureCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeletePictureCompleted);
            }
            base.InvokeAsync(this.onBeginDeletePictureDelegate, new object[] {
                        wordId}, this.onEndDeletePictureDelegate, this.onDeletePictureCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VocalRecall.SuggestopediaService.ISuggestopediaService CreateChannel() {
            return new SuggestopediaServiceClientChannel(this);
        }
        
        private class SuggestopediaServiceClientChannel : ChannelBase<VocalRecall.SuggestopediaService.ISuggestopediaService>, VocalRecall.SuggestopediaService.ISuggestopediaService {
            
            public SuggestopediaServiceClientChannel(System.ServiceModel.ClientBase<VocalRecall.SuggestopediaService.ISuggestopediaService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDeleteWords(int cultureId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = cultureId;
                System.IAsyncResult _result = base.BeginInvoke("DeleteWords", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteWords(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteWords", _args, result);
            }
            
            public System.IAsyncResult BeginUploadWords(int cultureId, System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> words, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = cultureId;
                _args[1] = words;
                System.IAsyncResult _result = base.BeginInvoke("UploadWords", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUploadWords(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("UploadWords", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListCultures(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ListCultures", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture> EndListCultures(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture> _result = ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Culture>)(base.EndInvoke("ListCultures", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginAuthenticateUser(string username, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("AuthenticateUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndAuthenticateUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("AuthenticateUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetUserInfo(string username, int sessionId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = sessionId;
                System.IAsyncResult _result = base.BeginInvoke("GetUserInfo", _args, callback, asyncState);
                return _result;
            }
            
            public VocalRecall.SuggestopediaService.UserInfo EndGetUserInfo(System.IAsyncResult result) {
                object[] _args = new object[0];
                VocalRecall.SuggestopediaService.UserInfo _result = ((VocalRecall.SuggestopediaService.UserInfo)(base.EndInvoke("GetUserInfo", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWord(int wordId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = wordId;
                System.IAsyncResult _result = base.BeginInvoke("GetWord", _args, callback, asyncState);
                return _result;
            }
            
            public VocalRecall.SuggestopediaService.Word EndGetWord(System.IAsyncResult result) {
                object[] _args = new object[0];
                VocalRecall.SuggestopediaService.Word _result = ((VocalRecall.SuggestopediaService.Word)(base.EndInvoke("GetWord", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetTranslation(int wordId, int cultureId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = wordId;
                _args[1] = cultureId;
                System.IAsyncResult _result = base.BeginInvoke("GetTranslation", _args, callback, asyncState);
                return _result;
            }
            
            public VocalRecall.SuggestopediaService.Word EndGetTranslation(System.IAsyncResult result) {
                object[] _args = new object[0];
                VocalRecall.SuggestopediaService.Word _result = ((VocalRecall.SuggestopediaService.Word)(base.EndInvoke("GetTranslation", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWords(int cultureId, int frequencyMinimum, int frequencyMaximum, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = cultureId;
                _args[1] = frequencyMinimum;
                _args[2] = frequencyMaximum;
                System.IAsyncResult _result = base.BeginInvoke("GetWords", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> EndGetWords(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> _result = ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word>)(base.EndInvoke("GetWords", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGet10Words(int cultureId, int top, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = cultureId;
                _args[1] = top;
                System.IAsyncResult _result = base.BeginInvoke("Get10Words", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> EndGet10Words(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word> _result = ((System.Collections.ObjectModel.ObservableCollection<VocalRecall.SuggestopediaService.Word>)(base.EndInvoke("Get10Words", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeletePicture(int wordId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = wordId;
                System.IAsyncResult _result = base.BeginInvoke("DeletePicture", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeletePicture(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeletePicture", _args, result);
            }
        }
    }
}
